run:
  concurrency: 4
  skip-dirs:
    - third_party$
    - builtin$
    - examples$

linters:
  enable:
    - revive
    - godox
    - errcheck
    - misspell
    - staticcheck
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: true
  misspell:
    locale: US
  revive:
    rules:
      - name: blank-imports
      - name: unused-parameter
  godox:
    keywords:
      - TODO
      - FIXME
      - BUG
  staticcheck:
    checks:
      - all
      - -ST1000
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/iDWELL/finance