version: "2"

run:
  concurrency: 4

linters:
  enable:
    #- misspell
    - revive
    - godot
    - godox
    #- unparam
  settings:
    errcheck:
      check-blank: true
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: unused-parameter
    godox:
      keywords:
        - TODO
        - FIXME
        - BUG
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
