receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    limit_mib: 512
    check_interval: 1s
  
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: false

exporters:
  # Prometheus metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: loci_templui
    const_labels:
      service: loci-templui
  
  # Prometheus remote write
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
  
  # Tempo tracing via HTTP
  otlp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  
  # Loki logging
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Debug logging
  debug:
    verbosity: detailed

service:
  pipelines:
    # Metrics pipeline
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [prometheus, prometheusremotewrite, debug]
    
    # Traces pipeline
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [otlp/tempo, debug]
    
    # Logs pipeline
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [loki, debug]
  
  extensions: []
  
  telemetry:
    logs:
      level: "debug"
    metrics:
      level: detailed
